DEPTH_MIN_M = 0.0
DEPTH_MAX_M = 25.0
COLOR_MAP = "viridis"

GRID_INTERVAL_M = 1.0
GRID_INTERVAL_TARGETS_M = 2.0
GRIDDED_TARGET_MIN_POINTS_PER_CELL = 20

UNGRIDDED_LOG_EVERY_MESSAGES = 1
GRIDDED_LOG_EVERY_MESSAGES = 10
GRIDDED_SURFACE_LOG_EVERY_MESSAGES = 30

TIN_TUNING_FACTOR = 5.0
TIN_MIN_EDGE = 4.0
